name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet
          # Se você tiver um requirements.txt, use: pip install -r requirements.txt

      - name: Build APK
        run: flet build apk --target kmeans.py

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dash-analyzer-apk
          path: build/apk/*.apk
