name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Prepare and Build
        run: |
          # 1. Renomeia o seu arquivo para main.py (o que o Flet exige)
          cp AnaliseDash.py main.py
          
          # 2. Executa o build apontando para o diretório atual
          # O ponto '.' indica que o main.py está aqui
          flet build apk .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-skins-dash
          path: "**/build/apk/*.apk"
