name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Prepare and Build
        run: |
          # 1. Encontra o arquivo não importa onde ele esteja e move para a raiz real
          FILE_FOUND=$(find . -name "AnaliseDash.py" -print -quit)
          cp "$FILE_FOUND" ./main_app.py
          
          # 2. Executa o build no arquivo que acabamos de colocar na raiz
          flet build apk main_app.py

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-skins-dash
          path: "**/build/apk/*.apk"

          
